#!/usr/bin/env bash
# bash scritp that do alotof...
# create file
# echo something when reciving  SIGNAL
# kill alos the process when reciving a SIGNAL

ahshit() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && ahshit' SIGTERM
	trap 'ahshit' SIGQUITgit
done
