#!/usr/bin/env bash
#bash scritp that do alotof...

echo "$$" > /var/run/myscript.pid
whie true
do
	echo "To infinity and beyond"
	trap 'echo "I hate the kill command"' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm /var/run/myscript.pid' SIGQUIT SIGTERM
done
